services:
  api:
    build:
      context: .
    restart: always
    expose:
      - 80
    volumes:
      - ./:/app
    ports:
      - 5001:80
    depends_on:
      - db
    links:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db:
      image: postgres
      restart: always
      shm_size: 128mb
      expose:
        - 5432
      ports:
        - 5432:5432
      volumes:
        - database_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}

volumes:
  database_data:
    driver: local
